# Generated by Django 3.0.7 on 2020-06-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0005_image_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
