# Generated by Django 3.0.7 on 2020-06-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0010_auto_20200608_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profilephoto',
            field=models.ImageField(upload_to='profile/'),
        ),
    ]
