# Generated by Django 3.0.7 on 2020-06-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pics', '0017_auto_20200609_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(max_length=50),
        ),
    ]
